intu=int(123)
print(intu)
print(type(intu))
floatu=float(123)
print(floatu)
print(type(floatu))
stru=str("123")# str(123) & str('123')
print(stru)
print(type(stru))
listu=list('123')#  list('123')
print(listu)
print(type(listu))
setu=set("123") #set('123')
print(setu)
print(type(setu))
tupu=tuple('123')#set("123")
print(tupu)
print(type(tupu))
dictu=dict(a=1,b=2,c=3) # Key valur pair# here a,b,c are the keys and 1,2,3 are the values
print(dictu)
print(type(dictu))
boolu=bool(1)
print(boolu)
print(type(boolu))
bytu=bytes(5)
print(bytu)
print(type(bytu))
compleu=complex(5, 6)
print(compleu)
print(type(compleu))