itr=("hero","Heroine","Dinga")
print(itr)
itr1=("zero","Dingi","Chenge","Bombay")
print(itr1)
print(itr+itr1)
new_tuple=itr+itr1
print(new_tuple)
new_tuple2=(itr,itr1)
print(new_tuple2)
print("Starts Game")
print(itr[0])
print(itr1[1])
print(itr1[3])
print(new_tuple[0])
print(new_tuple2[1])
print(new_tuple2[1][2])
